name: no_finish_line_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+2
  http: ^0.13.5
  localstorage: ^4.0.0+1
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  transition: ^2.0.2
flutter:


  uses-material-design: true

