name: no_finish_line_app
description: A Flutter-based application used as a personal fitness logger.


publish_to: 'none' 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

flutter_icons:
  image_path: "assets/images/no_end.png"
  android: true
  ios: true

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+2
  http: ^0.13.5
  localstorage: ^4.0.0+1
  pie_chart: ^5.3.2
  firebase_core: ^1.22.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  transition: ^2.0.2

