// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';
import 'package:loading_animation_widget/loading_animation_widget.dart';

const String API_BASE_URL = 'https://no-finish-line.herokuapp.com/';
const String API_AUTH_KEY = 'aac48d6f-b63d-47a8-ada0-731db9955679';
const Color THEME_COLOR = Color.fromRGBO(0, 71, 113, 1);
const Color TEXT_COLOR = Color.fromRGBO(116, 89, 116, 1);

void showLoadingConst(context) {
  showDialog(
    barrierDismissible: false,
    context: context,
    builder: (context) => Center(
      child: Container(
        width: 60.0,
        height: 60.0,
        decoration: BoxDecoration(
          color: Colors.transparent,
          borderRadius: BorderRadius.circular(4.0),
        ),
        child: Padding(
            padding: const EdgeInsets.all(12.0),
            child: LoadingAnimationWidget.fourRotatingDots(
                color: THEME_COLOR, size: 60)),
      ),
    ),
  );
}

List<String> workouts = [
  'Internal Rotation with Band',
  'Spinal Stretch',
  'Extended Range One-Arm Kettlebell Floor Press',
  'Incline Bench Pull',
  'Single-Arm Linear Jammer',
  'Posterior Tibialis Stretch',
  'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl',
  'Split Squat with Dumbbells',
  'Oblique Crunches',
  'All Fours Quad Stretch',
  'Barbell Seated Calf Raise',
  'Triceps Pushdown - Rope Attachment',
  'Single Leg Push-off',
  'Band Hip Adductions',
  'Box Squat with Bands',
  'Peroneals-SMR',
  'Overhead Lat',
  'Hack Squat',
  'Front Cable Raise',
  'Bench Sprint',
  'Concentration Curls',
  'Cable Chest Press',
  'Hanging Pike',
  'Crossover Reverse Lunge',
  'Push Up to Side Plank',
  'Bodyweight Flyes',
  'Narrow Stance Leg Press',
  'Bent Over Dumbbell Rear Delt Raise With Head On Bench',
  'One-Arm Flat Bench Dumbbell Flye',
  'Hang Snatch',
  'Isometric Neck Exercise - Sides',
  'Butterfly',
  'Heaving Snatch Balance',
  'Single Leg Butt Kick',
  'Front Plate Raise',
  'Kettlebell Arnold Press',
  'Low Cable Triceps Extension',
  'Suspended Split Squat',
  'Kneeling Arm Drill',
  'Leg-Over Floor Press',
  'Foot-SMR',
  'Side to Side Box Shuffle',
  'Barbell Full Squat',
  'Seated Head Harness Neck Resistance',
  'Preacher Curl',
  'Pin Presses',
  'Upper Back Stretch',
  'Bottoms-Up Clean From The Hang Position',
  'Squat with Plate Movers',
  'Pallof Press',
  'Wide-Grip Pulldown Behind The Neck',
  'Power Stairs',
  'Plie Dumbbell Squat',
  'Suspended Fallout',
  'Lower Back Curl',
  'Superman',
  'Bench Press - Powerlifting',
  'Front Box Jump',
  'Kneeling Jump Squat',
  'Hyperextensions (Back Extensions)',
  'Dynamic Chest Stretch',
  'Frankenstein Squat',
  'Seated One-Arm Dumbbell Palms-Down Wrist Curl',
  'Stride Jump Crossover',
  'Seated Leg Curl',
  'One Arm Against Wall',
  'Bent Press',
  'Skating',
  'Flat Bench Cable Flyes',
  'Jerk Balance',
  'Lying Dumbbell Tricep Extension',
  'Side Laterals to Front Raise',
  'Cable Incline Triceps Extension',
  'Standing Calf Raises',
  'Sled Overhead Triceps Extension',
  'One Arm Dumbbell Preacher Curl',
  'Backward Medicine Ball Throw',
  'Bench Press - With Bands',
  'Gorilla Chin/Crunch',
  'Leverage Chest Press',
  'Lying Face Down Plate Neck Resistance',
  'Seated Bent-Over Rear Delt Raise',
  'One Arm Chin-Up',
  'Kettlebell Turkish Get-Up (Lunge style)',
  'Kneeling Cable Crunch With Alternating Oblique Twists',
  'Incline Cable Chest Press',
  'Dumbbell Seated One-Leg Calf Raise',
  'Smith Machine Hang Power Clean',
  'Bent Over Barbell Row',
  'Lying Close-Grip Barbell Triceps Press To Chin',
  'Incline Push-Up Medium',
  'Speed Band Overhead Triceps',
  'Decline Smith Press',
  'Barbell Curls Lying Against An Incline',
  'Standing Hip Flexors',
  'Zottman Preacher Curl',
  'Seated Dumbbell Palms-Down Wrist Curl',
  'Linear Acceleration Wall Drill',
  'Standing Rope Crunch',
  'Quad Stretch',
  'Single-Arm Cable Crossover',
  'Tuck Crunch',
  'Standing Concentration Curl',
  'Bicycling, Stationary',
  'Standing Military Press',
  'Intermediate Groin Stretch',
  'Incline Push-Up Reverse Grip',
  'One-Arm Kettlebell Para Press',
  'Double Kettlebell Jerk',
  'Sled Row',
  'Seated Floor Hamstring Stretch',
  'Hang Clean - Below the Knees',
  'Standing Inner-Biceps Curl',
  'Standing Biceps Cable Curl',
  'Mountain Climbers',
  'Otis-Up',
  'Full Range-Of-Motion Lat Pulldown',
  'Front Cone Hops (or hurdle hops)',
  'Leg Pull-In',
  'Standing Two-Arm Overhead Throw',
  'Bear Crawl Sled Drags',
  'IT Band and Glute Stretch',
  'Seated Cable Rows',
  'Tire Flip',
  'Barbell Lunge',
  'Good Morning',
  'Barbell Hack Squat',
  'Around The Worlds',
  'One-Arm Kettlebell Push Press',
  'Dumbbell Tricep Extension -Pronated Grip',
  'Seated Glute',
  'Torso Rotation',
  'Wide-Grip Lat Pulldown',
  'Plate Twist',
  'One-Arm Kettlebell Jerk',
  'Dumbbell One-Arm Upright Row',
  'EZ-Bar Curl',
  'Power Snatch',
  'Calf Stretch Elbows Against Wall',
  'Cable Crunch',
  'Single Dumbbell Raise',
  'T-Bar Row with Handle',
  'Kettlebell Hang Clean',
  'Chain Press',
  'Behind Head Chest Stretch',
  'One Arm Supinated Dumbbell Triceps Extension',
  'Medicine Ball Chest Pass',
  'Flat Bench Leg Pull-In',
  'Piriformis-SMR',
  'Lateral Bound',
  'Alternating Deltoid Raise',
  'Push Press',
  'Standing One-Arm Dumbbell Curl Over Incline Bench',
  'Upright Cable Row',
  'Svend Press',
  'Seated Good Mornings',
  'Alternate Incline Dumbbell Curl',
  'Cable Incline Pushdown',
  'Seated Dumbbell Curl',
  'Palms-Down Dumbbell Wrist Curl Over A Bench',
  'Parallel Bar Dip',
  'Walking, Treadmill',
  'Elbow to Knee',
  'External Rotation with Cable',
  'Rack Delivery',
  'Cross-Body Crunch',
  'Lying Close-Grip Bar Curl On High Pulley',
  'Straight Bar Bench Mid Rows',
  'Front Incline Dumbbell Raise',
  'Bent-Arm Dumbbell Pullover',
  'Lunge Pass Through',
  'Side Lying Groin Stretch',
  'Push-Up Wide',
  'Jogging, Treadmill',
  'Decline EZ Bar Triceps Extension',
  'Double Kettlebell Alternating Hang Clean',
  'Alternating Cable Shoulder Press',
  'Crunch - Hands Overhead',
  'Close-Grip Standing Barbell Curl',
  'Front Squat (Clean Grip)',
  'Chest And Front Of Shoulder Stretch',
  'Cable Crossover',
  'Side-Lying Floor Stretch',
  'Rowing, Stationary',
  'Chair Squat',
  'Standing One-Arm Dumbbell Triceps Extension',
  'Donkey Calf Raises',
  'Face Pull',
  'Chin To Chest Stretch',
  'Two-Arm Kettlebell Military Press',
  'Sled Drag - Harness',
  'Dumbbell Seated Box Jump',
  'Suspended Row',
  'Band Pull Apart',
  'Plyo Kettlebell Pushups',
  'Scissors Jump',
  'Bent Over Two-Dumbbell Row With Palms In',
  'Moving Claw Series',
  'Cable Shoulder Press',
  'Standing Palm-In One-Arm Dumbbell Press',
  'Frog Sit-Ups',
  'Overhead Stretch',
  'Medicine Ball Scoop Throw',
  'Two-Arm Dumbbell Preacher Curl',
  'Dumbbell Floor Press',
  'Seated Dumbbell Palms-Up Wrist Curl',
  'Dumbbell Alternate Bicep Curl',
  'One-Arm Kettlebell Clean and Jerk',
  'Toe Touchers',
  'Iron Crosses (stretch)',
  'Keg Load',
  'Reverse Grip Bent-Over Rows',
  'Incline Hammer Curls',
  'Goblet Squat',
  'Stomach Vacuum',
  'Bottoms Up',
  'Trap Bar Deadlift',
  'Spell Caster',
  'Cable Lying Triceps Extension',
  'Side Jackknife',
  'Mixed Grip Chin',
  'Chest Push from 3 point stance',
  'Windmills',
  'Reverse Band Power Squat',
  'Leg Press',
  'Narrow Stance Squats',
  'Weighted Pull Ups',
  'Standing Palms-Up Barbell Behind The Back Wrist Curl',
  'Clean Pull',
  'Reverse Band Deadlift',
  'Seated Leg Tucks',
  'Kneeling Forearm Stretch',
  'Underhand Cable Pulldowns',
  'Hip Extension with Bands',
  'Log Lift',
  'One Arm Lat Pulldown',
  'Barbell Deadlift',
  'Cable Internal Rotation',
  'Speed Squats',
  'Smith Machine Bench Press',
  'Tricep Side Stretch',
  'Standing Soleus And Achilles Stretch',
  'Oblique Crunches - On The Floor',
  'Smith Single-Leg Split Squat',
  'Standing Olympic Plate Hand Squeeze',
  'Squats - With Bands',
  'Lunge Sprint',
  'Isometric Chest Squeezes',
  'One-Arm Kettlebell Row',
  'Rope Crunch',
  'Bent Over Low-Pulley Side Lateral',
  'Power Snatch from Blocks',
  'Elevated Back Lunge',
  'Bent Over Two-Arm Long Bar Row',
  'Trail Running/Walking',
  'Platform Hamstring Slides',
  'Standing Cable Wood Chop',
  'Rope Straight-Arm Pulldown',
  'Open Palm Kettlebell Clean',
  'Pyramid',
  'Decline Close-Grip Bench To Skull Crusher',
  'Triceps Overhead Extension with Rope',
  'Weighted Jump Squat',
  'Leverage Shrug',
  'Snatch from Blocks',
  'Bodyweight Walking Lunge',
  'Air Bike',
  'Kneeling High Pulley Row',
  'Sled Overhead Backward Walk',
  'Box Skip',
  'Anti-Gravity Press',
  'Balance Board',
  'Standing Hamstring and Calf Stretch',
  'Clean from Blocks',
  'Chin-Up',
  'One-Arm Kettlebell Snatch',
  'One-Arm High-Pulley Cable Side Bends',
  'Reverse Plate Curls',
  'Side Hop-Sprint',
  'Arnold Dumbbell Press',
  'Split Jump',
  'Standing Bent-Over Two-Arm Dumbbell Triceps Extension',
  'Muscle Snatch',
  'Step-up with Knee Raise',
  'Brachialis-SMR',
  'Snatch Balance',
  'Deadlift with Chains',
  'Plate Pinch',
  'Pullups',
  'Upright Row - With Bands',
  'Standing Elevated Quad Stretch',
  'Standing Dumbbell Triceps Extension',
  'Dead Bug',
  "Conan's Wheel",
  'Seated Bent-Over One-Arm Dumbbell Triceps Extension',
  'Triceps Pushdown - V-Bar Attachment',
  'Power Jerk',
  'Reverse Triceps Bench Press',
  'Hug Knees To Chest',
  'Lying Prone Quadriceps',
  'Cable Reverse Crunch',
  'Barbell Shrug',
  'Dip Machine',
  'Dumbbell Bench Press',
  'Incline Dumbbell Curl',
  'Sumo Deadlift',
  'Suspended Reverse Crunch',
  "Runner's Stretch",
  'Close-Grip Dumbbell Press',
  'One-Arm Kettlebell Clean',
  'One-Arm Long Bar Row',
  'Star Jump',
  'Elbows Back',
  'Seated Side Lateral Raise',
  'Push Press - Behind the Neck',
  'Overhead Slam',
  'Kettlebell Thruster',
  'Squat with Chains',
  'Dumbbell Lying Pronation',
  'Good Morning off Pins',
  'Incline Dumbbell Bench With Palms Facing In',
  'Band Good Morning',
  'Straight Raises on Incline Bench',
  'Crunches',
  'Linear Depth Jump',
  'Incline Push-Up Wide',
  'Rhomboids-SMR',
  'Rope Climb',
  "World's Greatest Stretch",
  "Landmine 180's",
  'Supine One-Arm Overhead Throw',
  'Dumbbell Bicep Curl',
  'Leg-Up Hamstring Stretch',
  'Standing Dumbbell Straight-Arm Front Delt Raise Above Head',
  'Prowler Sprint',
  'Neck-SMR',
  'Standing Overhead Barbell Triceps Extension',
  'Push-Ups - Close Triceps Position',
  'Box Squat with Chains',
  'Front Barbell Squat',
  'Smith Machine Close-Grip Bench Press',
  'Jefferson Squats',
  'Zercher Squats',
  'Elliptical Trainer',
  'Single-Leg Leg Extension',
  'Flutter Kicks',
  'Reverse Flyes',
  'Inchworm',
  'Double Kettlebell Push Press',
  'Decline Barbell Bench Press',
  'Kettlebell Seesaw Press',
  'Overhead Cable Curl',
  'Chair Leg Extended Stretch',
  'Standing Cable Chest Press',
  'Clean and Press',
  'Incline Dumbbell Flyes',
  'Leg Extensions',
  'Leverage Shoulder Press',
  'Lying Leg Curls',
  'V-Bar Pulldown',
  'Incline Push-Up Close-Grip',
  'Split Squats',
  'Glute Kickback',
  'Handstand Push-Ups',
  'Sled Push',
  'Rack Pulls',
  'Kneeling Hip Flexor',
  'Landmine Linear Jammer',
  'Hammer Curls',
  'Dumbbell Squat',
  'Freehand Jump Squat',
  'Alternating Kettlebell Row',
  'One-Arm Open Palm Kettlebell Clean',
  'V-Bar Pullup',
  'Leverage Incline Chest Press',
  'Dumbbell Lunges',
  'Press Sit-Up',
  'Kneeling Cable Triceps Extension',
  'Double Kettlebell Snatch',
  'Palms-Up Barbell Wrist Curl Over A Bench',
  'Leverage High Row',
  'Speed Box Squat',
  'Push-Ups With Feet Elevated',
  'Decline Dumbbell Triceps Extension',
  'Wrist Rotations with Straight Bar',
  'JM Press',
  'Seated Calf Raise',
  'Floor Glute-Ham Raise',
  'Board Press',
  'One Handed Hang',
  'Latissimus Dorsi-SMR',
  'Car Drivers',
  'Close-Grip EZ-Bar Curl with Band',
  'Dumbbell Raise',
  'Kettlebell Dead Clean',
  'Rope Jumping',
  'Ring Dips',
  'Palms-Up Dumbbell Wrist Curl Over A Bench',
  'Wide-Grip Barbell Bench Press',
  'One Leg Barbell Squat',
  'Lying Supine Dumbbell Curl',
  'Bosu Ball Cable Crunch With Side Bends',
  'Alternating Floor Press',
  'Side Leg Raises',
  'Vertical Swing',
  'Barbell Rear Delt Row',
  'Rear Leg Raises',
  'Barbell Ab Rollout',
  'Peroneals Stretch',
  'Decline Oblique Crunch',
  'Standing Barbell Press Behind Neck',
  'Seated Barbell Military Press',
  'Cable Rear Delt Fly',
  'Medicine Ball Full Twist',
  'External Rotation with Band',
  'Calf Press',
  'Scapular Pull-Up',
  'Car Deadlift',
  'Standing Long Jump',
  'Lateral Raise - With Bands',
  'Wide Stance Stiff Legs',
  'Weighted Ball Hyperextension',
  'Cable Judo Flip',
  'Seated Palms-Down Barbell Wrist Curl',
  'Dumbbell Side Bend',
  'Straight-Arm Dumbbell Pullover',
  'Incline Push-Up Depth Jump',
  'Weighted Crunches',
  'Cocoons',
  'Kneeling Single-Arm High Pulley Row',
  'Spider Crawl',
  'Physioball Hip Bridge',
  'Upright Barbell Row',
  'Bent-Arm Barbell Pullover',
  'Snatch Shrug',
  'Cable One Arm Tricep Extension',
  'Reverse Grip Triceps Pushdown',
  'Barbell Step Ups',
  'Box Jump (Multiple Response)',
  'Smith Incline Shoulder Raise',
  'Scissor Kick',
  'Standing Dumbbell Reverse Curl',
  'Lying Hamstring',
  'The Straddle',
  'Machine Bicep Curl',
  'Quick Leap',
  'Standing Alternating Dumbbell Press',
  'Deadlift with Bands',
  'London Bridges',
  'Hamstring Stretch',
  'Incline Inner Biceps Curl',
  'Barbell Squat',
  'Reverse Crunch',
  'Standing Front Barbell Raise Over Head',
  'Pushups',
  'Kettlebell Windmill',
  'Overhead Triceps',
  'Weighted Bench Dip',
  'Axle Deadlift',
  'Chest Push (single response)',
  'Side Bridge',
  'Thigh Abductor',
  'Rocking Standing Calf Raise',
  'Exercise Ball Crunch',
  'Barbell Walking Lunge',
  'Kettlebell One-Legged Deadlift',
  'Standing Toe Touches',
  'Hang Snatch - Below Knees',
  'Clean',
  'Dumbbell Incline Row',
  'Sandbag Load',
  'Front Raise And Pullover',
  'Cable Rope Overhead Triceps Extension',
  'Russian Twist',
  'Kettlebell Seated Press',
  'Atlas Stones',
  'Kettlebell Pistol Squat',
  'Backward Drag',
  'Smith Machine Overhead Shoulder Press',
  'Chest Stretch on Stability Ball',
  'Iron Cross',
  'Hamstring-SMR',
  'Rack Pull with Bands',
  'Decline Crunch',
  'Shoulder Raise',
  'Glute Ham Raise',
  'Lying Triceps Press',
  'Finger Curls',
  'Lateral Box Jump',
  'Drag Curl',
  'Leverage Deadlift',
  'Barbell Side Split Squat',
  'Forward Drag with Press',
  'Reverse Band Sumo Deadlift',
  'Inverted Row with Straps',
  'Standing Dumbbell Upright Row',
  'Single-Arm Push-Up',
  'Groiners',
  'Barbell Shrug Behind The Back',
  'Seated Front Deltoid',
  'Rocket Jump',
  'Hyperextensions With No Hyperextension Bench',
  'Lying Close-Grip Barbell Triceps Extension Behind The Head',
  'Smith Machine Bent Over Row',
  'Alternating Hang Clean',
  'Cross Over - With Bands',
  'Kipping Muscle Up',
  'Step Mill',
  'Deficit Deadlift',
  'Shoulder Stretch',
  'Side Standing Long Jump',
  'Calf Stretch Hands Against Wall',
  'Band Good Morning (Pull Through)',
  '90/90 Hamstring',
  'Bent-Knee Hip Raise',
  'Clock Push-Up',
  'Crunch - Legs On Exercise Ball',
  'Advanced Kettlebell Windmill',
  'Leg Lift',
  'Supine Two-Arm Overhead Throw',
  'Wide Stance Barbell Squat',
  'Decline Dumbbell Flyes',
  'Machine Shoulder (Military) Press',
  'Power Clean',
  'Middle Back Stretch',
  'Smith Machine Stiff-Legged Deadlift',
  'Groin and Back Stretch',
  'Chair Upper Body Stretch',
  'Close-Grip Barbell Bench Press',
  'Bent Over Two-Dumbbell Row',
  'Cable Seated Crunch',
  'Supine Chest Throw',
  'Double Kettlebell Windmill',
  'Kettlebell Pirate Ships',
  'Linear 3-Part Start Technique',
  'Cable Shrugs',
  'Cuban Press',
  'Reverse Band Box Squat',
  'Stairmaster',
  'Knee Tuck Jump',
  'Dumbbell Lying Rear Lateral Raise',
  'Dumbbell One-Arm Triceps Extension',
  'Bent Over One-Arm Long Bar Row',
  'Reverse Barbell Curl',
  'Standing Dumbbell Press',
  'Romanian Deadlift',
  'Double Leg Butt Kick',
  'Single-Leg High Box Squat',
  'Cable Rope Rear-Delt Rows',
  'Power Partials',
  'Leverage Decline Chest Press',
  'Machine Preacher Curls',
  'Running, Treadmill',
  'Elbow Circles',
  'Frog Hops',
  'Standing Towel Triceps Extension',
  'Standing Leg Curl',
  'Pushups (Close and Wide Hand Positions)',
  'One-Arm Side Deadlift',
  'Standing Gastrocnemius Calf Stretch',
  'Chest Push with Run Release',
  'Tate Press',
  'Bench Dips',
  'One-Arm Kettlebell Split Jerk',
  'One-Legged Cable Kickback',
  'Carioca Quick Step',
  'Ab Roller',
  'Pelvic Tilt Into Bridge',
  'One Knee To Chest',
  'Low Pulley Row To Neck',
  'Chest Push (multiple response)',
  'Recumbent Bike',
  'Cable Preacher Curl',
  'Standing Pelvic Tilt',
  'Barbell Glute Bridge',
  'Seated Dumbbell Press',
  'Kettlebell Turkish Get-Up (Squat style)',
  'Standing Biceps Stretch',
  'Weighted Ball Side Bend',
  'Lying High Bench Barbell Curl',
  'Lying Crossover',
  'Ab Crunch Machine',
  'Kneeling Squat',
  'Floor Press with Chains',
  'See-Saw Press (Alternating Side Press)',
  'Rocky Pull-Ups/Pulldowns',
  'Seated Biceps',
  'Thigh Adductor',
  'Seated Hamstring',
  'Decline Reverse Crunch',
  'Elevated Cable Rows',
  'Isometric Wipers',
  'Dips - Triceps Version',
  'Seated Hamstring and Calf Stretch',
  'Split Jerk',
  'Lying T-Bar Row',
  'Seated Overhead Stretch',
  'Spider Curl',
  'Dumbbell Scaption',
  '3/4 Sit-Up',
  'Fast Skipping',
  'Standing One-Arm Cable Curl',
  'Drop Push',
  'Two-Arm Kettlebell Clean',
  'Alternating Renegade Row',
  'Lying Glute',
  'Tricep Dumbbell Kickback',
  'Dumbbell Shrug',
  'Calf Raises - With Bands',
  'Front Two-Dumbbell Raise',
  'Rickshaw Deadlift',
  'Decline Dumbbell Bench Press',
  'Adductor',
  'Hanging Leg Raise',
  'Dumbbell Rear Lunge',
  'Seated Band Hamstring Curl',
  'Seated Cable Shoulder Press',
  'Smith Machine Hip Raise',
  'Wrist Roller',
  "Dancer's Stretch",
  'Standing Dumbbell Calf Raise',
  'Lying Cambered Barbell Row',
  'Wind Sprints',
  'Cable Deadlifts',
  'Plyo Push-up',
  'Dumbbell Squat To A Bench',
  'Sumo Deadlift with Bands',
  'Standing Lateral Stretch',
  'Lying Cable Curl',
  'Smith Machine Upright Row',
  'Alternate Heel Touchers',
  'Plank',
  'EZ-Bar Skullcrusher',
  'Reverse Machine Flyes',
  'Monster Walk',
  'Olympic Squat',
  'Atlas Stone Trainer',
  'Single-Cone Sprint Drill',
  'Reverse Cable Curl',
  'One-Arm Dumbbell Row',
  'Smith Machine Squat',
  'One-Arm Medicine Ball Slam',
  'Dumbbell Flyes',
  'Leverage Iso Row',
  'Box Squat',
  'Two-Arm Kettlebell Row',
  'Floor Press',
  'Incline Cable Flye',
  'Round The World Shoulder Stretch',
  'Cat Stretch',
  'Seated One-Arm Dumbbell Palms-Up Wrist Curl',
  'Middle Back Shrug',
  'Kettlebell Sumo High Pull',
  'Calf Press On The Leg Press Machine',
  'Machine Bench Press',
  'One-Arm Side Laterals',
  'Cable Hip Adduction',
  'Hurdle Hops',
  'Push-Ups With Feet On An Exercise Ball',
  'Two-Arm Kettlebell Jerk',
  'Overhead Squat',
  'Close-Grip Push-Up off of a Dumbbell',
  'Front Dumbbell Raise',
  'Alternate Hammer Curl',
  'Stiff-Legged Dumbbell Deadlift',
  'Split Clean',
  'Seated Flat Bench Leg Pull-In',
  'Crucifix',
  'Kettlebell Pass Between The Legs',
  'Neck Press',
  'Kettlebell Figure 8',
  'Single-Leg Lateral Hop',
  'Smith Machine Decline Press',
  'Zottman Curl',
  'Seated Dumbbell Inner Biceps Curl',
  'Reverse Band Bench Press',
  'Weighted Sissy Squat',
  'Snatch Pull',
  'One-Arm Incline Lateral Raise',
  'Dynamic Back Stretch',
  'Barbell Side Bend',
  'Incline Barbell Triceps Extension',
  'Adductor/Groin',
  'Barbell Shoulder Press',
  'Low Cable Crossover',
  'Knee Circles',
  'Cable Wrist Curl',
  'Squat with Bands',
  'Bench Press with Chains',
  'Side To Side Chins',
  'Lower Back-SMR',
  'Standing Palms-In Dumbbell Press',
  'Back Flyes - With Bands',
  'Seated One-arm Cable Pulley Rows',
  'Knee Across The Body',
  'Incline Dumbbell Flyes - With A Twist',
  'Suspended Push-Up',
  'Wide-Grip Standing Barbell Curl',
  'Smith Machine Behind the Back Shrug',
  'External Rotation',
  'Downward Facing Balance',
  'Muscle Up',
  'Yoke Walk',
  'Squat Jerk',
  'Calf-Machine Shoulder Shrug',
  'Band Assisted Pull-Up',
  "Child's Pose",
  'Seated Close-Grip Concentration Barbell Curl',
  'Smith Machine Incline Bench Press',
  'Ball Leg Curl',
  'Triceps Pushdown',
  'Jackknife Sit-Up',
  'Standing Hip Circles',
  'Snatch',
  'Iliotibial Tract-SMR',
  'Dips - Chest Version',
  'Bodyweight Mid Row',
  'Incline Dumbbell Press',
  'Gironda Sternum Chins',
  'Battling Ropes',
  'Pull Through',
  'Seated Bent-Over Two-Arm Dumbbell Triceps Extension',
  'Circus Bell',
  'Bodyweight Squat',
  'One-Arm Kettlebell Military Press To The Side',
  'Smith Machine Calf Raise',
  'One-Arm Kettlebell Floor Press',
  'Wide-Grip Rear Pull-Up',
  'Dumbbell Clean',
  'Sit Squats',
  'Standing Bent-Over One-Arm Dumbbell Triceps Extension',
  'Return Push from Stance',
  'Upward Stretch',
  'Butt-Ups',
  'Ankle On The Knee',
  'Lateral Cone Hops',
  'Front Squats With Two Kettlebells',
  'Barbell Hip Thrust',
  'Dumbbell Incline Shoulder Raise',
  'Quadriceps-SMR',
  'Hip Lift with Band',
  'Inverted Row',
  'One Arm Floor Press',
  'Alternating Kettlebell Press',
  'Side Wrist Pull',
  'Lying Machine Squat',
  'One-Arm Kettlebell Split Snatch',
  'Hammer Grip Incline DB Bench Press',
  'Shoulder Press - With Bands',
  'Hang Clean',
  'Wrist Circles',
  'Palms-Down Wrist Curl Over A Bench',
  'Reverse Barbell Preacher Curls',
  'Machine Triceps Extension',
  'Sumo Deadlift with Chains',
  'Preacher Hammer Dumbbell Curl',
  'Catch and Overhead Throw',
  'Weighted Sit-Ups - With Bands',
  'Barbell Ab Rollout - On Knees',
  'Single Leg Glute Bridge',
  'Incline Push-Up',
  'Knee/Hip Raise On Parallel Bars',
  'Sledgehammer Swings',
  "Farmer's Walk",
  'Close-Grip Front Lat Pulldown',
  'Standing Bradford Press',
  'Barbell Guillotine Bench Press',
  'Dumbbell Lying Supination',
  'Lying Rear Delt Raise',
  'Seated Triceps Press',
  'Body-Up',
  'Sit-Up',
  'Single-Leg Hop Progression',
  'Weighted Squat',
  'Depth Jump Leap',
  'Upper Back-Leg Grab',
  'Barbell Bench Press - Medium Grip',
  'Split Snatch',
  'Cable Iron Cross',
  'High Cable Curls',
  'Seated Palm-Up Barbell Wrist Curl',
  'Anterior Tibialis-SMR',
  'Straight-Arm Pulldown',
  'Jerk Dip Squat',
  'Power Clean from Blocks',
  'Heavy Bag Thrust',
  'Lying One-Arm Lateral Raise',
  'Standing Low-Pulley Deltoid Raise',
  'Romanian Deadlift from Deficit',
  'Standing Cable Lift',
  'Clean and Jerk',
  'Looking At Ceiling',
  'Calf Raise On A Dumbbell',
  'Seated Barbell Twist',
  'Cable Seated Lateral Raise',
  'Narrow Stance Hack Squats',
  'Bradford/Rocky Presses',
  'Barbell Rollout from Bench',
  'Lying Face Up Plate Neck Resistance',
  'Shoulder Circles',
  'Rickshaw Carry',
  'Reverse Flyes With External Rotation',
  'Janda Sit-Up',
  'Butt Lift (Bridge)',
  'Dumbbell Step Ups',
  'One-Arm Kettlebell Swings',
  'Stiff-Legged Barbell Deadlift',
  'On Your Side Quad Stretch',
  'Flexor Incline Dumbbell Curls',
  'Clean Deadlift',
  'Sled Reverse Flye',
  'Alternate Leg Diagonal Bound',
  'One Arm Pronated Dumbbell Triceps Extension',
  'Hip Flexion with Band',
  'Flat Bench Lying Leg Raise',
  'Close-Grip EZ-Bar Press',
  'Clean Shrug',
  'Hug A Ball',
  'Side Lateral Raise',
  'Side Neck Stretch',
  'Lying Bent Leg Groin',
  'Cable Hammer Curls - Rope Attachment',
  'Front Barbell Squat To A Bench',
  'Isometric Neck Exercise - Front And Back',
  'Dumbbell Prone Incline Curl',
  'Arm Circles',
  'Dumbbell Bench Press with Neutral Grip',
  'One-Arm Overhead Kettlebell Squats',
  'Seated Calf Stretch',
  'Cable Russian Twists',
  'Stiff Leg Barbell Good Morning',
  'Smith Machine Reverse Calf Raises',
  'Shotgun Row',
  'Natural Glute Ham Raise',
  'Chain Handle Extension',
  'Dumbbell One-Arm Shoulder Press',
  'Body Tricep Press',
  'Smith Machine Leg Press',
  'Front Leg Raises',
  'Hanging Bar Good Morning',
  'Decline Push-Up',
  'Barbell Curl',
  'Snatch Deadlift',
  'Hip Circles (prone)',
  'Pallof Press With Rotation',
  'On-Your-Back Quad Stretch',
  'One Arm Dumbbell Bench Press',
  'Intermediate Hip Flexor and Quad Stretch',
  'One Half Locust',
  'Standing Low-Pulley One-Arm Triceps Extension',
  'Prone Manual Hamstring',
  'Barbell Incline Shoulder Raise',
  'Dumbbell Lying One-Arm Rear Lateral Raise',
  'Barbell Incline Bench Press - Medium Grip',
  'Wide-Grip Decline Barbell Bench Press',
  'Wide-Grip Decline Barbell Pullover',
  'Dumbbell Shoulder Press',
  'Exercise Ball Pull-In',
  'Calves-SMR',
  'Close-Grip EZ Bar Curl',
  'Bench Jump',
  'Barbell Squat To A Bench',
  'Chair Lower Back Stretch',
  'Standing Barbell Calf Raise',
  'Bicycling',
  'Cross Body Hammer Curl',
  'Band Skull Crusher',
  'Ankle Circles',
  'Smith Machine Pistol Squat',
  'Triceps Stretch',
  'Smith Machine One-Arm Upright Row',
  'Reverse Hyperextension',
  'Single-Leg Stride Jump'
];
