// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpqDi3WY5isjAGv61T7e-Y40dIBGubCs',
    appId: '1:166725160194:web:cd783b42f033234261061b',
    messagingSenderId: '166725160194',
    projectId: 'nofinishline-137fa',
    authDomain: 'nofinishline-137fa.firebaseapp.com',
    storageBucket: 'nofinishline-137fa.appspot.com',
    measurementId: 'G-2BQJKHPTW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBH5touhdl6Z0icROD2ry3qu9jFqDfAA',
    appId: '1:166725160194:android:5ac60204a9f2c49561061b',
    messagingSenderId: '166725160194',
    projectId: 'nofinishline-137fa',
    storageBucket: 'nofinishline-137fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EpaRYmFXAt7KXxYwIq4j__p3B8TcJgw',
    appId: '1:166725160194:ios:2e770393a3ad6e1761061b',
    messagingSenderId: '166725160194',
    projectId: 'nofinishline-137fa',
    storageBucket: 'nofinishline-137fa.appspot.com',
    iosClientId: '166725160194-sdl3rpjeig2fr7oo526i4nhek7pvt541.apps.googleusercontent.com',
    iosBundleId: 'com.example.noFinishLineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EpaRYmFXAt7KXxYwIq4j__p3B8TcJgw',
    appId: '1:166725160194:ios:2e770393a3ad6e1761061b',
    messagingSenderId: '166725160194',
    projectId: 'nofinishline-137fa',
    storageBucket: 'nofinishline-137fa.appspot.com',
    iosClientId: '166725160194-sdl3rpjeig2fr7oo526i4nhek7pvt541.apps.googleusercontent.com',
    iosBundleId: 'com.example.noFinishLineApp',
  );
}
